### ISSUE TITLE
Fails to build with opencv 3.4.2

### ISSUE THREAD

**Issue by dbermond** [dyne/frei0r#26]
I'm getting this compile error when using the newly released opencv 3.4.2:

```
filter/facebl0r/facebl0r.cpp: In member function ‘virtual void FaceBl0r::update(double, uint32_t*, const uint32_t*)’:
filter/facebl0r/facebl0r.cpp:224:45: error: ‘CV_RGB’ was not declared in this scope
               cvEllipseBox(image, face_box, CV_RGB(255,0,0), 2, CV_AA, 0);
                                             ^~~~~~
filter/facebl0r/facebl0r.cpp:224:45: note: suggested alternative: ‘CV_C’
               cvEllipseBox(image, face_box, CV_RGB(255,0,0), 2, CV_AA, 0);
                                             ^~~~~~
                                             CV_C
```

It builds fine when using opencv 3.4.1.

It seems that the macro `CV_RGB` is not defined anymore in opencv 3.4.2.

**System Information:**
**OS:** Arch Linux x86_64
**Compiler:** gcc 8.1.1
**frei0r-plugins:** git master
**opencv:** 3.4.2

**Comment by cwilling** [comment]
I see the same problem here (Slackware64-14.2). I've submitted PR #27 which fixes the issue for me.

**Comment by jaromil** [comment]
PR merged! thanks.
