### ISSUE TITLE
2.5.0 fails to build with error in tint0r (due to SSE4.1)

### ISSUE THREAD

**Issue by tgurr** [dyne/frei0r#228]
Build failure (complete build log [frei0r-plugins-2.5.0.log.txt](https://github.com/user-attachments/files/23727343/frei0r-plugins-2.5.0.log.txt)):

```
[...]
[ 59%] Building C object src/filter/tint0r/CMakeFiles/tint0r.dir/tint0r.c.o
cd /var/tmp/paludis/build/media-plugins-frei0r-plugins-2.5.0/work/build/src/filter/tint0r && /usr/bin/x86_64-pc-linux-gnu-cc -Dtint0r_EXPORTS -I/var/tmp/paludis/build/media-plugins-frei0r-plugins-2.5.0/work/frei0r-2.5.0/include -march=native -O2 -pipe -fPIC -fdiagnostics-color=always -MD -MT src/filter/tint0r/CMakeFiles/tint0r.dir/tint0r.c.o -MF CMakeFiles/tint0r.dir/tint0r.c.o.d -o CMakeFiles/tint0r.dir/tint0r.c.o -c /var/tmp/paludis/build/media-plugins-frei0r-plugins-2.5.0/work/frei0r-2.5.0/src/filter/tint0r/tint0r.c
make[2]: Leaving directory '/var/tmp/paludis/build/media-plugins-frei0r-plugins-2.5.0/work/build'
make[1]: Leaving directory '/var/tmp/paludis/build/media-plugins-frei0r-plugins-2.5.0/work/build'

/var/tmp/paludis/build/media-plugins-frei0r-plugins-2.5.0/work/frei0r-2.5.0/src/filter/tint0r/tint0r.c: In function 'f0r_update':
/var/tmp/paludis/build/media-plugins-frei0r-plugins-2.5.0/work/frei0r-2.5.0/src/filter/tint0r/tint0r.c:196:9: error: incompatible types when assigning to type '__m128' from type '__m128i'
  196 |     p = _mm_loadu_si128((__m128i*)inframe);
      |         ^~~~~~~~~~~~~~~
/var/tmp/paludis/build/media-plugins-frei0r-plugins-2.5.0/work/frei0r-2.5.0/src/filter/tint0r/tint0r.c:199:44: error: incompatible type for argument 1 of '_mm_cvtepu8_epi32'
  199 |     p0 = _mm_cvtepi32_ps(_mm_cvtepu8_epi32(p));
      |                                            ^
      |                                            |
      |                                            __m128
In file included from /var/tmp/paludis/build/media-plugins-frei0r-plugins-2.5.0/work/frei0r-2.5.0/src/filter/tint0r/tint0r.c:26:
/usr/x86_64-pc-linux-gnu/lib/gcc/x86_64-pc-linux-gnu/15/include/smmintrin.h:521:28: note: expected '__m128i' but argument is of type '__m128'
  521 | _mm_cvtepu8_epi32 (__m128i __X)
      |                    ~~~~~~~~^~~
/var/tmp/paludis/build/media-plugins-frei0r-plugins-2.5.0/work/frei0r-2.5.0/src/filter/tint0r/tint0r.c:200:59: error: incompatible type for argument 1 of '_mm_srli_si128'
  200 |     p1 = _mm_cvtepi32_ps(_mm_cvtepu8_epi32(_mm_srli_si128(p, 4)));
      |                                                           ^
      |                                                           |
      |                                                           __m128
In file included from /usr/x86_64-pc-linux-gnu/lib/gcc/x86_64-pc-linux-gnu/15/include/pmmintrin.h:31,
                 from /usr/x86_64-pc-linux-gnu/lib/gcc/x86_64-pc-linux-gnu/15/include/tmmintrin.h:31,
                 from /usr/x86_64-pc-linux-gnu/lib/gcc/x86_64-pc-linux-gnu/15/include/smmintrin.h:32:
/usr/x86_64-pc-linux-gnu/lib/gcc/x86_64-pc-linux-gnu/15/include/emmintrin.h:1228:25: note: expected '__m128i' but argument is of type '__m128'
 1228 | _mm_srli_si128 (__m128i __A, const int __N)
      |                 ~~~~~~~~^~~
/var/tmp/paludis/build/media-plugins-frei0r-plugins-2.5.0/work/frei0r-2.5.0/src/filter/tint0r/tint0r.c:201:59: error: incompatible type for argument 1 of '_mm_srli_si128'
  201 |     p2 = _mm_cvtepi32_ps(_mm_cvtepu8_epi32(_mm_srli_si128(p, 8)));
      |                                                           ^
      |                                                           |
      |                                                           __m128
/usr/x86_64-pc-linux-gnu/lib/gcc/x86_64-pc-linux-gnu/15/include/emmintrin.h:1228:25: note: expected '__m128i' but argument is of type '__m128'
 1228 | _mm_srli_si128 (__m128i __A, const int __N)
      |                 ~~~~~~~~^~~
/var/tmp/paludis/build/media-plugins-frei0r-plugins-2.5.0/work/frei0r-2.5.0/src/filter/tint0r/tint0r.c:202:59: error: incompatible type for argument 1 of '_mm_srli_si128'
  202 |     p3 = _mm_cvtepi32_ps(_mm_cvtepu8_epi32(_mm_srli_si128(p, 12)));
      |                                                           ^
      |                                                           |
      |                                                           __m128
/usr/x86_64-pc-linux-gnu/lib/gcc/x86_64-pc-linux-gnu/15/include/emmintrin.h:1228:25: note: expected '__m128i' but argument is of type '__m128'
 1228 | _mm_srli_si128 (__m128i __A, const int __N)
      |                 ~~~~~~~~^~~
/var/tmp/paludis/build/media-plugins-frei0r-plugins-2.5.0/work/frei0r-2.5.0/src/filter/tint0r/tint0r.c:214:11: error: incompatible types when assigning to type '__m128' from type '__m128i'
  214 |       v = _mm_cvtps_epi32(v)
      |           ^~~~~~~~~~~~~~~
/var/tmp/paludis/build/media-plugins-frei0r-plugins-2.5.0/work/frei0r-2.5.0/src/filter/tint0r/tint0r.c:216:5: note: in expansion of macro 'tint'
  216 |     tint(p0); tint(p1); tint(p2); tint(p3);
      |     ^~~~
/var/tmp/paludis/build/media-plugins-frei0r-plugins-2.5.0/work/frei0r-2.5.0/src/filter/tint0r/tint0r.c:214:11: error: incompatible types when assigning to type '__m128' from type '__m128i'
  214 |       v = _mm_cvtps_epi32(v)
      |           ^~~~~~~~~~~~~~~
/var/tmp/paludis/build/media-plugins-frei0r-plugins-2.5.0/work/frei0r-2.5.0/src/filter/tint0r/tint0r.c:216:15: note: in expansion of macro 'tint'
  216 |     tint(p0); tint(p1); tint(p2); tint(p3);
      |               ^~~~
/var/tmp/paludis/build/media-plugins-frei0r-plugins-2.5.0/work/frei0r-2.5.0/src/filter/tint0r/tint0r.c:214:11: error: incompatible types when assigning to type '__m128' from type '__m128i'
  214 |       v = _mm_cvtps_epi32(v)
      |           ^~~~~~~~~~~~~~~
/var/tmp/paludis/build/media-plugins-frei0r-plugins-2.5.0/work/frei0r-2.5.0/src/filter/tint0r/tint0r.c:216:25: note: in expansion of macro 'tint'
  216 |     tint(p0); tint(p1); tint(p2); tint(p3);
      |                         ^~~~
/var/tmp/paludis/build/media-plugins-frei0r-plugins-2.5.0/work/frei0r-2.5.0/src/filter/tint0r/tint0r.c:214:11: error: incompatible types when assigning to type '__m128' from type '__m128i'
  214 |       v = _mm_cvtps_epi32(v)
      |           ^~~~~~~~~~~~~~~
/var/tmp/paludis/build/media-plugins-frei0r-plugins-2.5.0/work/frei0r-2.5.0/src/filter/tint0r/tint0r.c:216:35: note: in expansion of macro 'tint'
  216 |     tint(p0); tint(p1); tint(p2); tint(p3);
      |                                   ^~~~
/var/tmp/paludis/build/media-plugins-frei0r-plugins-2.5.0/work/frei0r-2.5.0/src/filter/tint0r/tint0r.c:219:43: error: incompatible type for argument 1 of '_mm_packus_epi32'
  219 |     p = _mm_packus_epi16(_mm_packus_epi32(p0, p1),
      |                                           ^~
      |                                           |
      |                                           __m128
/usr/x86_64-pc-linux-gnu/lib/gcc/x86_64-pc-linux-gnu/15/include/smmintrin.h:559:27: note: expected '__m128i' but argument is of type '__m128'
  559 | _mm_packus_epi32 (__m128i __X, __m128i __Y)
      |                   ~~~~~~~~^~~
/var/tmp/paludis/build/media-plugins-frei0r-plugins-2.5.0/work/frei0r-2.5.0/src/filter/tint0r/tint0r.c:219:47: error: incompatible type for argument 2 of '_mm_packus_epi32'
  219 |     p = _mm_packus_epi16(_mm_packus_epi32(p0, p1),
      |                                               ^~
      |                                               |
      |                                               __m128
/usr/x86_64-pc-linux-gnu/lib/gcc/x86_64-pc-linux-gnu/15/include/smmintrin.h:559:40: note: expected '__m128i' but argument is of type '__m128'
  559 | _mm_packus_epi32 (__m128i __X, __m128i __Y)
      |                                ~~~~~~~~^~~
/var/tmp/paludis/build/media-plugins-frei0r-plugins-2.5.0/work/frei0r-2.5.0/src/filter/tint0r/tint0r.c:220:43: error: incompatible type for argument 1 of '_mm_packus_epi32'
  220 |                          _mm_packus_epi32(p2, p3));
      |                                           ^~
      |                                           |
      |                                           __m128
/usr/x86_64-pc-linux-gnu/lib/gcc/x86_64-pc-linux-gnu/15/include/smmintrin.h:559:27: note: expected '__m128i' but argument is of type '__m128'
  559 | _mm_packus_epi32 (__m128i __X, __m128i __Y)
      |                   ~~~~~~~~^~~
/var/tmp/paludis/build/media-plugins-frei0r-plugins-2.5.0/work/frei0r-2.5.0/src/filter/tint0r/tint0r.c:220:47: error: incompatible type for argument 2 of '_mm_packus_epi32'
  220 |                          _mm_packus_epi32(p2, p3));
      |                                               ^~
      |                                               |
      |                                               __m128
/usr/x86_64-pc-linux-gnu/lib/gcc/x86_64-pc-linux-gnu/15/include/smmintrin.h:559:40: note: expected '__m128i' but argument is of type '__m128'
  559 | _mm_packus_epi32 (__m128i __X, __m128i __Y)
      |                                ~~~~~~~~^~~
/var/tmp/paludis/build/media-plugins-frei0r-plugins-2.5.0/work/frei0r-2.5.0/src/filter/tint0r/tint0r.c:222:42: error: incompatible type for argument 2 of '_mm_storeu_si128'
  222 |     _mm_storeu_si128((__m128i*)outframe, p);
      |                                          ^
      |                                          |
      |                                          __m128
/usr/x86_64-pc-linux-gnu/lib/gcc/x86_64-pc-linux-gnu/15/include/emmintrin.h:741:43: note: expected '__m128i' but argument is of type '__m128'
  741 | _mm_storeu_si128 (__m128i_u *__P, __m128i __B)
      |                                   ~~~~~~~~^~~
make[2]: *** [src/filter/tint0r/CMakeFiles/tint0r.dir/build.make:79: src/filter/tint0r/CMakeFiles/tint0r.dir/tint0r.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:6225: src/filter/tint0r/CMakeFiles/tint0r.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
```
Info:
```
$ cat /proc/cpuinfo 
processor       : 0
vendor_id       : GenuineIntel
cpu family      : 6
model           : 151
model name      : 12th Gen Intel(R) Core(TM) i5-12500
stepping        : 5
microcode       : 0x3a
cpu MHz         : 800.000
cache size      : 18432 KB
physical id     : 0
siblings        : 12
core id         : 0
cpu cores       : 6
apicid          : 0
initial apicid  : 0
fpu             : yes
fpu_exception   : yes
cpuid level     : 32
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb ssbd ibrs ibpb stibp ibrs_enhanced tpr_shadow flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid rdseed adx smap clflushopt clwb intel_pt sha_ni xsaveopt xsavec xgetbv1 xsaves split_lock_detect avx_vnni dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp hwp_pkg_req hfi vnmi umip pku ospke waitpkg gfni vaes vpclmulqdq rdpid movdiri movdir64b fsrm md_clear serialize pconfig arch_lbr ibt flush_l1d arch_capabilities
vmx flags       : vnmi preemption_timer posted_intr invvpid ept_x_only ept_ad ept_1gb flexpriority apicv tsc_offset vtpr mtf vapic ept vpid unrestricted_guest vapic_reg vid ple shadow_vmcs pml ept_violation_ve ept_mode_based_exec tsc_scaling usr_wait_pause
bugs            : spectre_v1 spectre_v2 spec_store_bypass swapgs eibrs_pbrsb bhi spectre_v2_user vmscape
bogomips        : 5990.40
clflush size    : 64
cache_alignment : 64
address sizes   : 46 bits physical, 48 bits virtual
power management:
[...]
```
GCC version 15.2.0 (but also happens with 14.3.0 & 13.3.0). Passing `-mno-sse4.1` to disable SSE4.1 allows the build to succeed.

**Comment by tgurr** [comment]
Was finally fixed by https://github.com/dyne/frei0r/commit/3713d779b46e04fb88d914a58287d8e717a70559 / https://github.com/dyne/frei0r/pull/285 included in https://github.com/dyne/frei0r/releases/tag/v3.3.0.
