### ISSUE TITLE
shake0scillate fails to build on macOS 12.7

### ISSUE THREAD

**Issue by ddennedy** [dyne/frei0r#294]
```
FAILED: src/filter/shake0scillate/CMakeFiles/shake0scillate.dir/shake0scillate.cpp.o 
/Library/Developer/CommandLineTools/usr/bin/c++ -Dshake0scillate_EXPORTS -I/Users/ddennedy/melt/src/frei0r/include -I/opt/local/include/cairo -O2 -g -DNDEBUG -std=gnu++11 -arch arm64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX13.1.sdk -mmacosx-version-min=12.7 -fPIC -MD -MT src/filter/shake0scillate/CMakeFiles/shake0scillate.dir/shake0scillate.cpp.o -MF src/filter/shake0scillate/CMakeFiles/shake0scillate.dir/shake0scillate.cpp.o.d -o src/filter/shake0scillate/CMakeFiles/shake0scillate.dir/shake0scillate.cpp.o -c /Users/ddennedy/melt/src/frei0r/src/filter/shake0scillate/shake0scillate.cpp
/Users/ddennedy/melt/src/frei0r/src/filter/shake0scillate/shake0scillate.cpp:91:54: error: no member named 'sin' in namespace 'std'
            x = movement_x * movement_range_x * std::sin(movement_speed_value_x + this->phase);
                                                ~~~~~^
/Users/ddennedy/melt/src/frei0r/src/filter/shake0scillate/shake0scillate.cpp:98:49: error: no member named 'cos' in namespace 'std'; did you mean 'cosl'?
            y = movement_y * movement_range_y * std::cos(movement_speed_value_y + this->phase);
                                                ^~~~~~~~
                                                cosl
/Library/Developer/CommandLineTools/SDKs/MacOSX13.1.sdk/usr/include/math.h:326:20: note: 'cosl' declared here
extern long double cosl(long double);
                   ^
/Users/ddennedy/melt/src/frei0r/src/filter/shake0scillate/shake0scillate.cpp:115:99: error: no member named 'sin' in namespace 'std'
            float rotation = ((this->rotation_amount - 0.5f) * ROTATION_AMOUNT_MULTIPLIER) * std::sin(rotation_speed_value) * M_PI;
                                                                                             ~~~~~^
3 errors generated.
```
